/*  A data class representing a task in the ToDo app.

    The class is instantiated with the following parameters:
        * title : String -> A short title for the task
        * description : String -> A short description
        * dueDate : Date -> When the task is due

    Other parameters include:
        * id : Int -> self-explanatory
        * creationData : Data -> autogenerated creation time
        * status : String -> represents if the task is (todo | late | complete)
        * deleted : Boolean -> represents if the task is deleted or not
 */

import java.util.Date

data class Task(
            val id: Int,
            val creationDate: Long = Date().getTime(),
            var dueDate: Long,
            val title: String,
            val description: String = "",
            var status: String = "todo",
            var deleted: Boolean = false) {
}